spring.application.name=app
# Afficher les requêtes SQL générées dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Activer les logs de niveau TRACE pour le binding des paramètres
logging.level.org.hibernate.orm.results=INFO
logging.level.org.springframework.web=DEBUG